### ISSUE TITLE
[Bug] When specifying self-signed cert, does not write the correct header for "https-certificate"

### ISSUE THREAD

**Issue by AnubisSec** [Tylous/SourcePoint#12]
Everything works great, I love this tool. The only issue is that when you don't specify a keystore for the certificate, the header for the section of "https-certificate" isn't written to the final profile.

The following command: 
`SourcePoint -Injector VirtualAllocEx -Jitter 21 -Keylogger SetWindowsHookEx -PE_Clone 24 -PostEX_Name 17 -Outfile deez.profile -Host www.bing.com -Profile 2`

Results in the following last 20 lines of the profile

```
$ tail -20 deez.profile

header "Cache-Control" "private, no-cache, no-store, must-revalidate";
header "X-Frame-Options" "SAMEORIGIN";
header "Vary" "Accept-Encoding";
header "X-Via" "haproxy-www-suhx";

}


}


set CN       "www.bing.com"; #Common Name
set O        "Slack Technologies Inc"; #Organization Name
set C        "US"; #Country
set L        "San Francisco"; #Locality
set OU       "DigiCert Inc"; #Organizational Unit Name
set ST       "CA"; #State or Province
set validity "365"; #Number of days the cert is valid for
}
        %
```

Note, right about `set CN` there is no `https-certificate {` as there should be

**Comment by Tylous** [comment]
Yes that is a odd logic bug I will have to look into

**Comment by Tylous** [comment]
This has been fixed in v2.3.

**Comment by Tylous** [comment]
the `\n` was causing the issue you originally reported. Are you still experiencing it?

**Comment by AnubisSec** [comment]
Yeah so there is just one other `\n` that is causing issues on MacOS seen below (one being the original file and one being the lib I updated to fix it):
![image](https://user-images.githubusercontent.com/38790814/174794346-d2119bd8-c08c-4b17-8172-5e2da1c35d74.png)

![image](https://user-images.githubusercontent.com/38790814/174794768-9221ce79-cb83-494c-820f-a9eb806397e8.png)
