### ISSUE TITLE
Cannot run with -PE_Clone 30

### ISSUE THREAD

**Issue by hsfetty** [Tylous/SourcePoint#16]
# 🐛 Summary #

There are 30 options for the PE_Clone, the last one being umppc.dll. When trying to specify #30, an error is thrown. This error comes from [Loader.go](https://github.com/Tylous/SourcePoint/blob/main/Loader/Loader.go#L93)

## To reproduce ##

1. Run SourcePoint with the parameter `-PE_Clone 30`

## Any helpful log output or screenshots ##

```console
[*] Preparing Varibles...
2022/07/08 15:49:17 Error: Please provide a valid PE number less the 31 option
```

Add any screenshots of the problem here.
![image](https://user-images.githubusercontent.com/64932388/178060998-03339290-4156-4335-bb21-cd6a90e9a643.png)

**Comment by Tylous** [comment]
Fixed in v2.4
