### ISSUE TITLE
Unknown string replace option kills powershell-import

### ISSUE THREAD

**Issue by tpmiller87** [Tylous/SourcePoint#21]
One of the string replace options kills the functionality of `powershell-import`.

Prior to running `powershell-import`, `powerpick` works fine. After importing Powerview, `powerpick` shows this error on any command (notice the simple `whoami`, it doesn't recognize any imported commands at all):

![image](https://github.com/Tylous/SourcePoint/assets/15959707/de402a5b-8f91-4ab9-8cab-2087028caca4)

I deleted all of the `strrep` lines in both x86 and x64 and both `powershell-import` and `powerpick` worked as intended.

Before I split the strreps into chunks to find the bad one (or couple), any ideas?

**Comment by Tylous** [comment]
Not sure, I'll have to test.

**Comment by Tylous** [comment]
I figured out the issue I will pushing out a fix shortly.

**Comment by Tylous** [comment]
There is a new version 3.0 that should address this.
