### ISSUE TITLE
escape characters in the magic_mz_x64

### ISSUE THREAD

**Issue by superuser5** [Tylous/SourcePoint#23]
when i generate new profile, it uses escape character '\\' for the magic_mz_x64 that causes c2lint errors.
I can regenerate or change it manually and works fine, no big deal. 

**error:**
```
[-] Error(s) while compiling /opt/my.profile
Error: unknown escape \A at line 58
       A\AT
         ^
[-] exiting because of errors in /opt/my.profile. Use ./c2lint to check the file

```

**string in my profile:**
```
set magic_mz_x64 "A\AT";
```

**Comment by Tylous** [comment]
odd it should be double \\ to be accepted. Ill take a look at it and back to you.

**Comment by Tylous** [comment]
Just pushed a fix for this.

**Comment by superuser5** [comment]
thank you, i tested and it fixed the issue.
