### ISSUE TITLE
Add HTTP Config Option (Feature Request)

### ISSUE THREAD

**Issue by kophjager007** [Tylous/SourcePoint#5]
Awesome project! Do you think you could add an additional option to set `trust_x_forwarded_for` in the `http-config` block for when using HTTP redirectors?

```bash
http-config{
    set trust_x_forwarded_for "true";
}
```

**Comment by Tylous** [comment]
Yeah I can this as an option. It might take be a minute but it’s doable

**Comment by Tylous** [comment]
Feature added in version 1.3
